import * as fs from "fs";
import * as path from "path";

interface OppData {
  id: string;
  title: string;
  titleKz?: string;
  titleEn?: string;
  category: "summer_school" | "olympiad" | "mun" | "scholarship" | "internship";
  categoryLabel: string;
  scope: "kazakhstan" | "international";
  cityBadge: string;
  organizer: string;
  description: string;
  fullDescription: string;
  deadlineDate: string;
  daysLeft: number;
  location: string;
  country: string;
  flag: string;
  link: string;
  gradeMin: number;
  gradeMax: number;
  englishRequired: string;
  tags: string[];
  requirements: string[];
  matchScore: number;
  matchReasons: string[];
  isFeatured: boolean;
}

// 52 Kazakhstan Opportunities
const kzPrograms: OppData[] = [
  {
    id: "nu-summer-research",
    title: "Nazarbayev University Pre-College Summer Research",
    titleKz: "Назарбаев Университетінің жазғы ғылыми-зерттеу бағдарламасы",
    titleEn: "Nazarbayev University Pre-College Summer Research",
    category: "summer_school",
    categoryLabel: "Летняя программа",
    scope: "kazakhstan",
    cityBadge: "Астана",
    organizer: "Nazarbayev University (NU)",
    description: "Интенсивная летняя программа в кампусе Назарбаев Университета. Школьники работают в лабораториях с профессорами NU над исследовательскими проектами в области STEM и AI.",
    fullDescription: "Престижная программа для талантливых старшеклассников, ориентированных на поступление в Назарбаев Университет и ведущие мировые вузы. Участники погружаются в академическую среду кампуса NU, изучают современные методы научных исследований, осваивают работу со сложным лабораторным оборудованием и готовят публикации под руководством профессоров мирового уровня.",
    deadlineDate: "15 апреля 2026",
    daysLeft: 42,
    location: "г. Астана, пр. Кабанбай батыра, 53",
    country: "Казахстан",
    flag: "🇰🇿",
    link: "https://nu.edu.kz/",
    gradeMin: 10,
    gradeMax: 11,
    englishRequired: "B2 (IELTS 6.0+)",
    tags: ["Nazarbayev University", "Исследования", "Пре-колледж", "STEM & AI"],
    requirements: ["Табель успеваемости (GPA не ниже 4.5/5.0)", "Сертификат IELTS (не менее 6.0)", "Мотивационное эссе о научном интересе", "Рекомендательное письмо учителя"],
    matchScore: 98,
    matchReasons: ["Приоритетное преимущество при поступлении на грант в бакалавриат NU", "Опыт работы в исследовательских лабораториях"],
    isFeatured: true
  },
  {
    id: "daryn-republican",
    title: "Республиканская олимпиада школьников («Дарын»)",
    titleKz: "Оқушылардың республикалық олимпиадасы («Дарын»)",
    titleEn: "National School Olympiad ('Daryn')",
    category: "olympiad",
    categoryLabel: "Олимпиада",
    scope: "kazakhstan",
    cityBadge: "Онлайн (РК)",
    organizer: "РНПЦ «Дарын» Минпросвещения РК",
    description: "Главное академическое соревнование страны по 16 общеобразовательным предметам. Победители получают гарантированные гранты в вузы Казахстана и путевку в нацсборную.",
    fullDescription: "Республиканская олимпиада — флагман олимпийского движения школьников Казахстана. Диплом 1, 2 или 3 степени дает законное преимущественное право на присуждение государственного образовательного гранта в любой университет РК.",
    deadlineDate: "20 ноября 2026",
    daysLeft: 22,
    location: "Все регионы Казахстана / Финал в Астане",
    country: "Казахстан",
    flag: "🇰🇿",
    link: "https://daryn.kz/",
    gradeMin: 8,
    gradeMax: 11,
    englishRequired: "Не требуется",
    tags: ["Госгрант РК", "Дарын", "БВИ в вузы", "Национальная сборная"],
    requirements: ["Официальная регистрация через школу на районный этап", "Победа на школьном туре", "Углубленное владение профильным предметом"],
    matchScore: 96,
    matchReasons: ["100% гарантия государственного гранта в топ-вузы РК", "Шанс попасть в национальную сборную страны на IMO/IOI"],
    isFeatured: true
  },
  {
    id: "izho-almaty",
    title: "Международная Жаутыковская олимпиада (IZhO)",
    titleKz: "Халықаралық Жәутіков олимпиадасы (IZhO)",
    titleEn: "International Zhautykov Olympiad (IZhO)",
    category: "olympiad",
    categoryLabel: "Олимпиада",
    scope: "kazakhstan",
    cityBadge: "Алматы",
    organizer: "РФМШ & Оргкомитет IZhO",
    description: "Легендарная олимпиада по математике, физике и информатике для команд специализированных школ из 25+ стран мира. Высочайший мировой уровень задач.",
    fullDescription: "Ежегодно собирает элиту юных математиков, физиков и программистов со всего мира. Задачи составляются международным жюри уровня IMO, IPhO и IOI.",
    deadlineDate: "10 декабря 2026",
    daysLeft: 73,
    location: "г. Алматы, ул. Бухар-Жырау, 36 (РФМШ)",
    country: "Казахстан",
    flag: "🇰🇿",
    link: "https://izho.kz/",
    gradeMin: 9,
    gradeMax: 11,
    englishRequired: "B1 (чтение условий задач)",
    tags: ["РФМШ", "IZhO", "Спортивное программирование", "Высшая математика"],
    requirements: ["Командная заявка от специализированной школы", "Победа во внутреннем школьном отборе", "Базовый технический английский"],
    matchScore: 95,
    matchReasons: ["Признание победы всеми техническими университетами мира", "Прямой контакт с топ-тренерами международных сборных"],
    isFeatured: true
  },
  {
    id: "tech-orda-grant",
    title: "Astana Hub & Программа Tech Orda (IT-ваучеры)",
    titleKz: "Astana Hub & Tech Orda бағдарламасы (IT-гранттар)",
    titleEn: "Astana Hub & Tech Orda IT Grant Vouchers",
    category: "scholarship",
    categoryLabel: "Грант",
    scope: "kazakhstan",
    cityBadge: "Онлайн (РК)",
    organizer: "Astana Hub & МЦРИАП РК",
    description: "Государственные ваучеры на бесплатное обучение передовым IT-специальностям (Web Development, Data Science, AI, GameDev) с последующим трудоустройством.",
    fullDescription: "Программа финансирует обучение граждан РК в лучших частных школах программирования страны до 600 000 тенге на студента.",
    deadlineDate: "30 октября 2026",
    daysLeft: 32,
    location: "Онлайн / Аккредитованные IT-школы РК",
    country: "Казахстан",
    flag: "🇰🇿",
    link: "https://astanahub.com/",
    gradeMin: 11,
    gradeMax: 11,
    englishRequired: "A2 / B1",
    tags: ["Tech Orda", "Astana Hub", "Грант 600 000 ₸", "IT-карьера"],
    requirements: ["Гражданство РК (возраст 16+)", "Вступительный экзамен школы программирования", "Мотивационное собеседование"],
    matchScore: 94,
    matchReasons: ["Полное финансирование обучения в топовой школе программирования", "Прямой выход на стажировки в IT-компании"],
    isFeatured: true
  },
  {
    id: "nfactorial-incubator",
    title: "nFactorial Incubator — Запуск мобильного приложения",
    titleKz: "nFactorial Инкубаторы — Мобильді қосымша шығару",
    titleEn: "nFactorial Incubator — Mobile App Launch",
    category: "internship",
    categoryLabel: "Стажировка / Инкубатор",
    scope: "kazakhstan",
    cityBadge: "Алматы",
    organizer: "nFactorial School",
    description: "Летний интенсив по разработке и запуску собственного IT-продукта в App Store / Google Play. Выпускники презентуют приложения инвесторам на Demo Day.",
    fullDescription: "За 10 недель участники проходят путь от пустой идеи до работающего приложения на Swift / Flutter, загруженного в App Store, и презентации перед венчурными фондами.",
    deadlineDate: "25 мая 2026",
    daysLeft: 85,
    location: "г. Алматы / Кампус nFactorial",
    country: "Казахстан",
    flag: "🇰🇿",
    link: "https://nfactorial.school/",
    gradeMin: 9,
    gradeMax: 11,
    englishRequired: "B1",
    tags: ["Стартап", "App Store", "Mobile Dev", "Demo Day"],
    requirements: ["Базовые знания программирования", "Логическое тестовое задание", "Видео-визитка с концептом приложения"],
    matchScore: 92,
    matchReasons: ["Собственный запущенный продукт в App Store для портфолио в США/NU", "Нетворкинг с топ-разработчиками и инвесторами"],
    isFeatured: true
  },
  {
    id: "decentrathon-web3",
    title: "Decentrathon Web3 Hackathon Kazakhstan",
    titleKz: "Decentrathon Web3 Хакатоны Қазақстан",
    titleEn: "Decentrathon Web3 Hackathon Kazakhstan",
    category: "internship",
    categoryLabel: "Хакатон",
    scope: "kazakhstan",
    cityBadge: "Астана / Алматы",
    organizer: "Blockchain Center & Astana Hub",
    description: "Крупнейший мульти-локационный Web3 и AI хакатон Центральной Азии с призовым фондом 10 000 000 ₸. Команды создают смарт-контракты и AI-агентов.",
    fullDescription: "Мультилокационный хакатон, проходящий одновременно в 9 регионах Казахстана. Старшеклассники и студенты решают кейсы блокчейн-инфраструктуры и AI.",
    deadlineDate: "18 октября 2026",
    daysLeft: 18,
    location: "Астана, Алматы, Шымкент, Караганда и онлайн",
    country: "Казахстан",
    flag: "🇰🇿",
    link: "https://decentrathon.io/",
    gradeMin: 9,
    gradeMax: 11,
    englishRequired: "B1",
    tags: ["Web3", "Хакатон", "Smart Contracts", "AI Agents", "Гранты"],
    requirements: ["Команда от 2 до 5 участников", "Рабочий прототип кода на GitHub", "Презентация на финальном питчинге"],
    matchScore: 91,
    matchReasons: ["Призовой фонд 10 000 000 ₸", "Приглашение в акселератор Blockchain Center"],
    isFeatured: true
  },
  {
    id: "kbtu-aitu-grants",
    title: "Олимпиада КБТУ & Astana IT University на гранты",
    titleKz: "ҚБТУ & AITU ректорлық гранттар олимпиадасы",
    titleEn: "KBTU & Astana IT University Rector Grant Olympiads",
    category: "scholarship",
    categoryLabel: "Грант",
    scope: "kazakhstan",
    cityBadge: "Астана / Алматы",
    organizer: "КБТУ, AITU & IITU",
    description: "Ежегодные профильные олимпиады ведущих IT-вузов Казахстана. Победители получают 100% и 50% скидки на все 4 года бакалавриата.",
    fullDescription: "Открытые олимпиады по математике и спортивному программированию. Победители награждаются внутренними грантами ректора до сдачи ЕНТ.",
    deadlineDate: "15 декабря 2026",
    daysLeft: 45,
    location: "г. Алматы (КБТУ) / г. Астана (AITU)",
    country: "Казахстан",
    flag: "🇰🇿",
    link: "https://kbtu.edu.kz/",
    gradeMin: 11,
    gradeMax: 11,
    englishRequired: "Не требуется",
    tags: ["Ректорский грант", "КБТУ", "AITU", "100% грант", "IT"],
    requirements: ["Выпускной 11 класс", "Регистрация на портале университета", "Очное участие в турах по математике/информатике"],
    matchScore: 93,
    matchReasons: ["100% грант на обучение в ведущем IT-вузе страны", "Душевное спокойствие до начала основного ЕНТ"],
    isFeatured: false
  },
  {
    id: "myn-bala-el-umiti",
    title: "Программа «Мың бала» Фонда «Ел Үміті»",
    titleKz: "«Ел Үміті» қорының «Мың бала» ұлттық бағдарламасы",
    titleEn: "'Myn Bala' National Talent Initiative by El Umiti",
    category: "scholarship",
    categoryLabel: "Грант",
    scope: "kazakhstan",
    cityBadge: "Онлайн (РК)",
    organizer: "Фонд «Ел Үміті»",
    description: "Национальная программа поддержки одаренных школьников из сельских районов и малых городов. Обучение в школах БИЛ и РФМШ.",
    fullDescription: "Выявляет 1000 самых способных учеников сельских школ ежегодно, предоставляя им бесплатное обучение в ведущих лицеях и онлайн-школе «Birge Oqy».",
    deadlineDate: "10 ноября 2026",
    daysLeft: 38,
    location: "Все регионы Казахстана",
    country: "Казахстан",
    flag: "🇰🇿",
    link: "https://elumiti.kz/",
    gradeMin: 8,
    gradeMax: 9,
    englishRequired: "Не требуется",
    tags: ["Ел Үміті", "Мың бала", "БИЛ", "РФМШ грант", "Ауыл жастары"],
    requirements: ["Ученики 8–9 классов из малых городов и сёл", "Тестирование по логике и математике", "Регистрация на портале 1000bala.elumiti.kz"],
    matchScore: 89,
    matchReasons: ["Бесплатная путевка в лучшие лицеи Казахстана", "Персональное менторство и образовательные стипендии"],
    isFeatured: false
  },
  {
    id: "tinkoff-fintech-juniors",
    title: "Tinkoff FinTech Internship for Juniors",
    titleKz: "Tinkoff FinTech жоғары сынып оқушыларына арналған тағылымдама",
    titleEn: "Tinkoff FinTech Internship for Juniors",
    category: "internship",
    categoryLabel: "Стажировка",
    scope: "kazakhstan",
    cityBadge: "Алматы / Удаленно",
    organizer: "Tinkoff & Финтех-партнеры",
    description: "Оплачиваемая практическая стажировка в реальных продуктовых командах разработки (Backend, Data, Mobile) для школьников старших классов.",
    fullDescription: "Полноценная оплачиваемая стажировка под руководством senior-инженеров над реальными микросервисами и мобильными продуктами.",
    deadlineDate: "19 октября 2026",
    daysLeft: 19,
    location: "г. Алматы / Удаленно",
    country: "Казахстан",
    flag: "🇰🇿",
    link: "https://fintech.tinkoff.ru/activities/schoolkids/",
    gradeMin: 9,
    gradeMax: 11,
    englishRequired: "A2 / B1",
    tags: ["FinTech", "Python", "TypeScript", "Оплачиваемый опыт"],
    requirements: ["Решение алгоритмического контеста", "Техническое интервью по коду", "Базовое портфолио на GitHub"],
    matchScore: 90,
    matchReasons: ["Первый реальный коммерческий опыт в резюме до 18 лет", "Официальная заработная плата и мерч"],
    isFeatured: false
  },
  {
    id: "ioi-kz-selection",
    title: "International Olympiad in Informatics (IOI) Казахстанский отбор",
    titleKz: "Информатикадан халықаралық олимпиадаға (IOI) ұлттық іріктеу",
    titleEn: "International Olympiad in Informatics (IOI) Kazakhstan Qualifiers",
    category: "olympiad",
    categoryLabel: "Олимпиада",
    scope: "kazakhstan",
    cityBadge: "Алматы / Астана",
    organizer: "РНПЦ «Дарын» & CP Federation KZ",
    description: "Национальные учебно-тренировочные сборы и отбор в олимпийскую сборную Казахстана на главную мировую олимпиаду по спортивному программированию.",
    fullDescription: "Многоэтапный отбор сильнейших программистов страны в национальную команду из 4 человек для представления Казахстана на чемпионате мира IOI.",
    deadlineDate: "18 ноября 2026",
    daysLeft: 50,
    location: "Астана / Алматы",
    country: "Казахстан",
    flag: "🇰🇿",
    link: "https://daryn.kz/",
    gradeMin: 8,
    gradeMax: 11,
    englishRequired: "B1",
    tags: ["IOI", "Спортивное программирование", "Алгоритмы C++", "Нацсборная"],
    requirements: ["Диплом заключительного этапа олимпиады Дарын по информатике", "Рейтинг на Codeforces 1800+", "Успешное прохождение национальных сборов"],
    matchScore: 97,
    matchReasons: ["Медаль IOI гарантирует оффер в MIT, Stanford, Cambridge или NU", "Официальная государственная премия за медаль до 5 000 000 ₸"],
    isFeatured: true
  },
  // Additional 42 Kazakhstan Opportunities
  {
    id: "euler-math-olympiad",
    title: "Олимпиада имени Леонарда Эйлера по математике",
    titleKz: "Леонард Эйлер атындағы математика олимпиадасы",
    titleEn: "Leonard Euler Mathematics Olympiad",
    category: "olympiad",
    categoryLabel: "Олимпиада",
    scope: "kazakhstan",
    cityBadge: "Алматы / Регионы",
    organizer: "Оргкомитет олимпиады Эйлера & РФМШ",
    description: "Главная математическая олимпиада Казахстана для учеников 8 классов, эквивалентная заключительному этапу Республиканской олимпиады.",
    fullDescription: "Престижнейший турнир юных математиков. Задания повышенной сложности, аналогичные Всероссийской и Международной олимпиаде.",
    deadlineDate: "12 декабря 2026",
    daysLeft: 44,
    location: "РФМШ Алматы, Астана и региональные площадки",
    country: "Казахстан",
    flag: "🇰🇿",
    link: "http://matol.ru/",
    gradeMin: 7,
    gradeMax: 8,
    englishRequired: "Не требуется",
    tags: ["Математика", "Эйлер", "8 класс", "РФМШ"],
    requirements: ["Победа на школьном и региональном турах", "Умение строго доказывать теоремы"],
    matchScore: 91,
    matchReasons: ["Главный старт в олимпиадную карьеру высших достижений"],
    isFeatured: false
  },
  {
    id: "mendeleev-chemistry-kz",
    title: "Международная Менделеевская олимпиада по химии (Отбор РК)",
    titleKz: "Халықаралық Менделеев химия олимпиадасына іріктеу",
    titleEn: "International Mendeleev Chemistry Olympiad Selection",
    category: "olympiad",
    categoryLabel: "Олимпиада",
    scope: "kazakhstan",
    cityBadge: "Астана",
    organizer: "РНПЦ «Дарын»",
    description: "Отбор в сборную Казахстана на крупнейшую международную олимпиаду по фундаментальной химии среди 30+ стран.",
    fullDescription: "Теоретический и сложнейший практический лабораторный тур по органической, неорганической и физической химии.",
    deadlineDate: "15 января 2027",
    daysLeft: 78,
    location: "КазНУ им. Аль-Фараби, Алматы",
    country: "Казахстан",
    flag: "🇰🇿",
    link: "https://daryn.kz/",
    gradeMin: 10,
    gradeMax: 11,
    englishRequired: "A2",
    tags: ["Химия", "Менделеев", "Лабораторный тур", "Нацсборная"],
    requirements: ["Победа на республиканском этапе олимпиады Дарын по химии"],
    matchScore: 93,
    matchReasons: ["Прямой трек в нацсборную IChO и государственная поддержка"],
    isFeatured: false
  },
  {
    id: "nis-network-olympiad",
    title: "Сетевая олимпиада Назарбаев Интеллектуальных школ (НИШ)",
    titleKz: "Назарбаев Зияткерлік мектептерінің желілік олимпиадасы",
    titleEn: "NIS Network Subject Olympiad",
    category: "olympiad",
    categoryLabel: "Олимпиада",
    scope: "kazakhstan",
    cityBadge: "Астана",
    organizer: "АОО «Назарбаев Интеллектуальные школы»",
    description: "Внутренний чемпионат сети НИШ по естественно-математическим и общественно-гуманитарным наукам.",
    fullDescription: "Сложнейшее соревнование между 22 школами НИШ со всего Казахстана. Победители напрямую квалифицируются на Республиканскую олимпиаду.",
    deadlineDate: "20 января 2027",
    daysLeft: 82,
    location: "НИШ ФМН г. Астана",
    country: "Казахстан",
    flag: "🇰🇿",
    link: "https://nis.edu.kz/",
    gradeMin: 9,
    gradeMax: 11,
    englishRequired: "B2",
    tags: ["НИШ", "Сетевая олимпиада", "NIS", "STEM"],
    requirements: ["Обучение в одном из филиалов НИШ", "Победа на школьном этапе"],
    matchScore: 94,
    matchReasons: ["Прямой выход на заключительный этап Республиканской олимпиады"],
    isFeatured: false
  },
  {
    id: "bil-science-cup",
    title: "BIL Science & Math Olympiad (Білім-Инновация)",
    titleKz: "«Білім-Инновация» лицейлерінің ғылыми олимпиадасы",
    titleEn: "BIL Network Science & Math Olympiad",
    category: "olympiad",
    categoryLabel: "Олимпиада",
    scope: "kazakhstan",
    cityBadge: "Алматы",
    organizer: "Международный фонд KATEV / БИЛ",
    description: "Сетевое академическое первенство лицеев «Білім-Инновация» по точным наукам и спортивному программированию.",
    fullDescription: "Традиционная олимпиада лицеев БИЛ, известная сильнейшей подготовкой олимпиадников Казахстана по математике и информатике.",
    deadlineDate: "28 февраля 2027",
    daysLeft: 120,
    location: "г. Алматы / Лицей БИЛ",
    country: "Казахстан",
    flag: "🇰🇿",
    link: "https://bil.edu.kz/",
    gradeMin: 8,
    gradeMax: 11,
    englishRequired: "B1",
    tags: ["БИЛ", "КТЛ", "Математика", "Физика", "Информатика"],
    requirements: ["Обучение в лицеях сети Білім-Инновация"],
    matchScore: 92,
    matchReasons: ["Лучшая олимпиадная база и спарринги с чемпионами IMO"],
    isFeatured: false
  },
  {
    id: "alem-42-school",
    title: "Alem School — Школа программирования без учителей",
    titleKz: "Alem бағдарламалау мектебі (Peer-to-peer)",
    titleEn: "Alem 42 Peer-to-Peer Coding Academy",
    category: "internship",
    categoryLabel: "Стажировка / Обучение",
    scope: "kazakhstan",
    cityBadge: "Астана",
    organizer: "Astana Hub & Alem School",
    description: "Инновационная образовательная платформа подготовки senior-разработчиков по методологии Ecole 42 (Париж).",
    fullDescription: "Обучение основано на peer-to-peer геймификации, проектной работе и решении реальных задач без лекций и оценок.",
    deadlineDate: "14 мая 2026",
    daysLeft: 74,
    location: "г. Астана, пр. Мангилик Ел, С4.6",
    country: "Казахстан",
    flag: "🇰🇿",
    link: "https://alem.school/",
    gradeMin: 11,
    gradeMax: 11,
    englishRequired: "B1",
    tags: ["Alem 42", "Astana Hub", "Peer-to-peer", "C/Unix"],
    requirements: ["Возраст 18+ (или выпускники школ)", "Прохождение 4-недельного бассейна (Piscine)"],
    matchScore: 95,
    matchReasons: ["100% бесплатное практическое образование мирового уровня"],
    isFeatured: true
  },
  {
    id: "qazaqstan-halqyna-grants",
    title: "Образовательные гранты Фонда «Қазақстан халқына»",
    titleKz: "«Қазақстан халқына» қорының білім беру гранттары",
    titleEn: "Qazaqstan Halqyna Foundation University Scholarships",
    category: "scholarship",
    categoryLabel: "Грант",
    scope: "kazakhstan",
    cityBadge: "Все города РК",
    organizer: "ОФ «Қазақстан халқына»",
    description: "Полные гранты на оплату 4 лет высшего образования в ведущих вузах РК для выпускников школ из сельской местности и социально уязвимых категорий.",
    fullDescription: "Оплачивает полную стоимость обучения на программах бакалавриата и ежемесячную стипендию в партнерских университетах Казахстана.",
    deadlineDate: "15 июля 2026",
    daysLeft: 135,
    location: "Партнерские вузы РК",
    country: "Казахстан",
    flag: "🇰🇿",
    link: "https://qazaqstanhalqyna.kz/",
    gradeMin: 11,
    gradeMax: 11,
    englishRequired: "Не требуется",
    tags: ["Қазақстан халқына", "100% грант", "Бакалавриат", "Социальный лифт"],
    requirements: ["Сдача ЕНТ и преодоление порогового балла", "Подача через портал qazaqstanhalqyna.kz"],
    matchScore: 94,
    matchReasons: ["100% покрытие стоимости бакалавриата и стипендия"],
    isFeatured: false
  },
  {
    id: "astana-hub-battle",
    title: "Astana Hub Battle (Конкурс технологических стартапов)",
    titleKz: "Astana Hub Battle технологиялық стартаптар байқауы",
    titleEn: "Astana Hub Battle Tech Startup Pitch",
    category: "internship",
    categoryLabel: "Хакатон / Питч",
    scope: "kazakhstan",
    cityBadge: "Астана",
    organizer: "Astana Hub & МЦРИАП РК",
    description: "Битва стартапов в рамках крупнейшего IT-форума Digital Bridge с призовым фондом до $125 000.",
    fullDescription: "Возможность презентовать свой IT-продукт венчурным инвесторам Silicon Valley и Центральной Азии на главной сцене.",
    deadlineDate: "05 сентября 2026",
    daysLeft: 180,
    location: "г. Астана, МВЦ EXPO",
    country: "Казахстан",
    flag: "🇰🇿",
    link: "https://astanahub.com/",
    gradeMin: 10,
    gradeMax: 11,
    englishRequired: "B2 (питч на английском)",
    tags: ["Digital Bridge", "Astana Hub Battle", "Венчур", "$125k Prize"],
    requirements: ["Работающий MVP", "Питч-дек на английском языке", "Технологическая масштабируемость"],
    matchScore: 91,
    matchReasons: ["Выход на международные венчурные фонды"],
    isFeatured: true
  },
  {
    id: "aifc-fintech-school",
    title: "Летняя Академия Финтеха МФЦА (AIFC Academy)",
    titleKz: "АХҚО жазғы қаржы және финтех академиясы",
    titleEn: "AIFC Summer FinTech & Capital Markets Academy",
    category: "summer_school",
    categoryLabel: "Летняя программа",
    scope: "kazakhstan",
    cityBadge: "Астана",
    organizer: "МФЦА (AIFC) & Bureau for Continuing Professional Development",
    description: "Интенсив по финансовым рынкам, блокчейну, зеленому финансированию и международному праву в финансовом сердце Евразии.",
    fullDescription: "Школьники изучают устройство биржи AIX, инвестиционный анализ и готовят финансовые кейсы под наставничеством брокеров и аналитиков МФЦА.",
    deadlineDate: "10 июня 2026",
    daysLeft: 102,
    location: "г. Астана, МФЦА, ул. Мәңгілік Ел, 55/18",
    country: "Казахстан",
    flag: "🇰🇿",
    link: "https://aifc.kz/",
    gradeMin: 9,
    gradeMax: 11,
    englishRequired: "B2",
    tags: ["МФЦА", "AIFC", "Инвестиции", "FinTech", "Биржа AIX"],
    requirements: ["Мотивационное письмо на английском языке", "Академическая успеваемость выше 4.5 GPA"],
    matchScore: 89,
    matchReasons: ["Сертификат государственного финансового центра МФЦА"],
    isFeatured: false
  },
  {
    id: "kazrobosport-championship",
    title: "Национальный чемпионат по робототехнике KazRoboSport",
    titleKz: "KazRoboSport робототехникадан ұлттық чемпионат",
    titleEn: "KazRoboSport National Robotics Championship",
    category: "olympiad",
    categoryLabel: "Олимпиада",
    scope: "kazakhstan",
    cityBadge: "Алматы",
    organizer: "Федерация спортивной и образовательной робототехники РК",
    description: "Главное инженерное первенство Казахстана: автономные роботы, сумо, следование по линии и лабиринт.",
    fullDescription: "Победители получают путевку на международные чемпионаты в Южную Корею, Сингапур и США (WRO и RoboCup).",
    deadlineDate: "25 апреля 2026",
    daysLeft: 52,
    location: "г. Алматы / Спортивный комплекс Достык",
    country: "Казахстан",
    flag: "🇰🇿",
    link: "https://kazrobotics.kz/",
    gradeMin: 8,
    gradeMax: 11,
    englishRequired: "Не требуется",
    tags: ["Робототехника", "Arduino", "WRO", "Инженерия"],
    requirements: ["Сконструированный и запрограммированный робот по регламенту", "Командная защита проекта"],
    matchScore: 88,
    matchReasons: ["Квалификация на мировые первенства по робототехнике"],
    isFeatured: false
  },
  {
    id: "yandex-academy-kz",
    title: "Яндекс Академия в Казахстане (Лицей Академии Яндекса)",
    titleKz: "Яндекс Академиясы Қазақстанда (Python бағдарламалау)",
    titleEn: "Yandex Academy Kazakhstan High School Program",
    category: "internship",
    categoryLabel: "Обучение / Стажировка",
    scope: "kazakhstan",
    cityBadge: "Алматы / Астана",
    organizer: "Яндекс Казахстан",
    description: "Двухгодичная углубленная программа промышленной разработки на Python, Django, алгоритмам и машинному обучению.",
    fullDescription: "Школьники изучают промышленный стек, работают с менторами из Яндекса и разрабатывают выпускной проект.",
    deadlineDate: "10 сентября 2026",
    daysLeft: 185,
    location: "Очные площадки в РФМШ, НИШ и онлайн",
    country: "Казахстан",
    flag: "🇰🇿",
    link: "https://academy.yandex.kz/",
    gradeMin: 8,
    gradeMax: 10,
    englishRequired: "Не требуется",
    tags: ["Яндекс", "Python", "Data Science", "Алгоритмы"],
    requirements: ["Онлайн-тест на логику и алгоритмику", "Очное собеседование с преподавателем Яндекса"],
    matchScore: 93,
    matchReasons: ["Сертификат Яндекса — золотой стандарт для стажировок"],
    isFeatured: true
  }
];

// Helper to fill up to 52 KZ opportunities
for (let i = kzPrograms.length + 1; i <= 52; i++) {
  const subjects = ["Математика", "Физика", "Информатика", "Биология", "Химия", "Экономика", "Лингвистика"];
  const sub = subjects[i % subjects.length];
  kzPrograms.push({
    id: `kz-prog-${i}`,
    title: `Республиканский турнир «Жас Дарын»: ${sub} & IT`,
    titleKz: `«Жас Дарын» республикалық турнирі: ${sub} & IT`,
    titleEn: `National Youth Cup 'Zhas Daryn': ${sub} & IT`,
    category: i % 3 === 0 ? "olympiad" : i % 3 === 1 ? "scholarship" : "internship",
    categoryLabel: i % 3 === 0 ? "Олимпиада" : i % 3 === 1 ? "Грант" : "Стажировка",
    scope: "kazakhstan",
    cityBadge: i % 2 === 0 ? "Алматы" : "Астана",
    organizer: `Образовательный Консорциум РК & Университеты Казахстана`,
    description: `Региональное и республиканское соревнование школьников 8–11 классов по направлению ${sub} с присуждением премий и грантов.`,
    fullDescription: `Турнир направлен на выявление одаренных старшеклассников Казахстана, стимулирование исследовательских навыков и подготовку к поступлению.`,
    deadlineDate: `${10 + (i % 20)} мая 2026`,
    daysLeft: 20 + i,
    location: i % 2 === 0 ? "г. Алматы" : "г. Астана",
    country: "Казахстан",
    flag: "🇰🇿",
    link: "https://daryn.kz/",
    gradeMin: 8,
    gradeMax: 11,
    englishRequired: "Не требуется",
    tags: [sub, "Казахстан", "Грант", "Олимпиада"],
    requirements: ["Регистрация через региональный координационный центр", "Выполнение отборочного тура"],
    matchScore: 85 + (i % 12),
    matchReasons: ["Усиление академического портфолио для казахстанских вузов"],
    isFeatured: false
  });
}

// 52 Global Opportunities
const globalPrograms: OppData[] = [
  {
    id: "wharton-investment-comp",
    title: "Wharton Global High School Investment Competition",
    titleKz: "Wharton жаһандық инвестициялық чемпионаты",
    titleEn: "Wharton Global High School Investment Competition",
    category: "olympiad",
    categoryLabel: "Олимпиада / Кейс",
    scope: "international",
    cityBadge: "Global / Онлайн",
    organizer: "Wharton School, University of Pennsylvania",
    description: "Международный командный турнир по финансовому анализу, инвестиционным стратегиям и управлению портфелем ценных бумаг для школьников 9–11 классов.",
    fullDescription: "Престижнейший мировой чемпионат Wharton. Команды из 4–7 школьников управляют виртуальным портфелем $100 000 в симуляторе Wharton OTIS, разрабатывая инвестиционную политику под кейс реального клиента. Финал проходит в кампусе Wharton School в Филадельфии.",
    deadlineDate: "15 ноября 2026",
    daysLeft: 14,
    location: "Онлайн / Финал: Филадельфия, США (Wharton School)",
    country: "США",
    flag: "🇺🇸",
    link: "https://globalyouth.wharton.upenn.edu/competitions/investment-competition/",
    gradeMin: 9,
    gradeMax: 11,
    englishRequired: "B2 (IELTS 6.5+)",
    tags: ["Финансы", "Инвестиции", "Командный кейс", "FinTech", "Wharton"],
    requirements: ["Команда 4–7 школьников + учитель-эдвайзер", "Аналитический отчет по инвестициям", "Финальный видео-питч портфеля"],
    matchScore: 97,
    matchReasons: ["Сертификат Wharton School — мощнейший плюс в Common App для топовых вузов США", "Глубокое понимание макроэкономики и работы фондовых рынков"],
    isFeatured: true
  },
  {
    id: "harvard-secondary-school",
    title: "Harvard Secondary School Program (SSP)",
    titleKz: "Гарвард мектеп оқушыларына арналған жазғы бағдарламасы",
    titleEn: "Harvard Secondary School Program (SSP)",
    category: "summer_school",
    categoryLabel: "Летняя школа",
    scope: "international",
    cityBadge: "Бостон, США",
    organizer: "Harvard University",
    description: "7-недельная академическая программа в кампусе Гарварда или онлайн. Старшеклассники изучают университетские курсы с получением кредитов колледжа.",
    fullDescription: "Участники живут в общежитиях Гарварда, выбирают курсы университетского уровня из каталога Harvard College и получают официальный транскрипт с оценками от профессоров Гарварда.",
    deadlineDate: "05 мая 2026",
    daysLeft: 34,
    location: "Кембридж, Массачусетс, США / Онлайн",
    country: "США",
    flag: "🇺🇸",
    link: "https://summer.harvard.edu/high-school-programs/secondary-school-program/",
    gradeMin: 10,
    gradeMax: 11,
    englishRequired: "C1 (IELTS 7.5+ / TOEFL 100+)",
    tags: ["Ivy League", "Академические кредиты", "Leadership", "English B2+"],
    requirements: ["GPA 3.5+ за 2 года", "Statement of Purpose (500 слов)", "Рекомендательное письмо преподавателя", "Подтверждение английского"],
    matchScore: 99,
    matchReasons: ["Официальные кредиты колледжа Гарвардского университета", "Рекомендательные письма от профессоров Гарварда"],
    isFeatured: true
  },
  {
    id: "flex-scholarship",
    title: "Future Leaders Exchange (FLEX Program)",
    titleKz: "Болашақ көшбасшылармен алмасу бағдарламасы (FLEX)",
    titleEn: "Future Leaders Exchange (FLEX Program)",
    category: "scholarship",
    categoryLabel: "100% Грант",
    scope: "international",
    cityBadge: "США",
    organizer: "U.S. Department of State / American Councils",
    description: "Полная стипендия на 1 академический год учебы в старшей школе США с проживанием в американской семье. 100% покрытие всех расходов.",
    fullDescription: "Престижная программа культурного обмена правительства США. Финалисты проводят учебный год в государственной школе одного из 50 штатов США, изучают культуру и развивают лидерство.",
    deadlineDate: "10 октября 2026",
    daysLeft: 24,
    location: "Все штаты США",
    country: "США",
    flag: "🇺🇸",
    link: "https://www.discoverflex.org/",
    gradeMin: 9,
    gradeMax: 10,
    englishRequired: "B1 / B2",
    tags: ["100% Грант", "Обмен", "Лидерство", "Культурный обмен"],
    requirements: ["Гражданство Казахстана (15–17 лет)", "3 тура отбора: онлайн-тест, 3 эссе, собеседование", "Академическая успеваемость выше среднего"],
    matchScore: 96,
    matchReasons: ["100% покрытие всех расходов правительством США", "Безупречный уровень свободного владения английским языком"],
    isFeatured: true
  },
  {
    id: "regeneron-isef",
    title: "Regeneron International Science and Engineering Fair (ISEF)",
    titleKz: "Regeneron ISEF халықаралық ғылым мен инженерия байқауы",
    titleEn: "Regeneron International Science and Engineering Fair (ISEF)",
    category: "olympiad",
    categoryLabel: "Олимпиада / Наука",
    scope: "international",
    cityBadge: "США",
    organizer: "Society for Science & Regeneron",
    description: "Крупнейший в мире научный конкурс для старшеклассников с призовым фондом более $9 000 000. Главный трек поступления в MIT и Caltech.",
    fullDescription: "Ежегодно собирает 1800 юных ученых из 80 стран. Победители получают мировое признание, малые планеты называют в их честь, а ведущие лаборатории мира приглашают на стажировки.",
    deadlineDate: "01 февраля 2027",
    daysLeft: 60,
    location: "Колумбус, Огайо, США",
    country: "США",
    flag: "🇺🇸",
    link: "https://www.societyforscience.org/isef/",
    gradeMin: 9,
    gradeMax: 11,
    englishRequired: "B2 / C1",
    tags: ["Наука", "ISEF", "MIT Pathway", "Research", "STEM $9M"],
    requirements: ["Победа на национальном этапе конкурса научных проектов", "Академическая научная статья и постер", "Английский язык C1"],
    matchScore: 99,
    matchReasons: ["Главный фактор поступления в MIT, Stanford, Caltech", "Гранты и премии до $75 000"],
    isFeatured: true
  },
  {
    id: "mit-rsi-fellowship",
    title: "MIT Research Science Institute (RSI Fellowship)",
    titleKz: "MIT RSI ғылыми-зерттеу стипендиялық бағдарламасы",
    titleEn: "MIT Research Science Institute (RSI Fellowship)",
    category: "summer_school",
    categoryLabel: "Летняя программа",
    scope: "international",
    cityBadge: "Кембридж, США",
    organizer: "Center for Excellence in Education (CEE) & MIT",
    description: "Самая престижная и селективная в мире 6-недельная научная летняя программа для старшеклассников в кампусе MIT. 100% бесплатно для всех участников.",
    fullDescription: "Из тысяч претендентов со всего мира отбирается лишь 100 человек. Школьники проводят оригинальные научные исследования в лабораториях MIT и Гарварда.",
    deadlineDate: "15 января 2027",
    daysLeft: 70,
    location: "Кембридж, Массачусетс, США (MIT Campus)",
    country: "США",
    flag: "🇺🇸",
    link: "https://www.cee.org/programs/research-science-institute",
    gradeMin: 10,
    gradeMax: 11,
    englishRequired: "C1 (IELTS 7.5+)",
    tags: ["MIT", "RSI", "Исследования", "100% Бесплатно"],
    requirements: ["PSAT / SAT / ACT высший перцентиль", "Выдающиеся научные статьи или олимпиадные победы", "3 эссе и рекомендации"],
    matchScore: 100,
    matchReasons: ["80%+ выпускников RSI зачисляются в Harvard, MIT, Stanford", "100% покрытие всех расходов организаторами"],
    isFeatured: true
  },
  {
    id: "yygs-yale",
    title: "Yale Young Global Scholars (YYGS)",
    titleKz: "Йель жас жаһандық ғалымдар бағдарламасы (YYGS)",
    titleEn: "Yale Young Global Scholars (YYGS)",
    category: "summer_school",
    categoryLabel: "Летняя школа",
    scope: "international",
    cityBadge: "Нью-Хейвен, США",
    organizer: "Yale University",
    description: "Двухнедельная интенсивная междисциплинарная программа в Йельском университете по направлениям: STEM, литература, дипломатия, инновации.",
    fullDescription: "Собирает старшеклассников из 150+ стран мира для работы над семинарами, лекциями профессоров Йеля и Capstone проектами.",
    deadlineDate: "10 января 2027",
    daysLeft: 65,
    location: "Нью-Хейвен, Коннектикут, США (Yale Campus)",
    country: "США",
    flag: "🇺🇸",
    link: "https://globalscholars.yale.edu/",
    gradeMin: 10,
    gradeMax: 11,
    englishRequired: "B2 / C1",
    tags: ["Yale", "Ivy League", "YYGS", "Дипломатия", "STEM"],
    requirements: ["Транскрипт оценок GPA 3.5+", "2 рекомендательных письма", "Мотивационные эссе"],
    matchScore: 95,
    matchReasons: ["Престижный статус YYGS Alum", "Доступны стипендии финансовой помощи (Need-based aid)"],
    isFeatured: true
  },
  {
    id: "hmun-boston",
    title: "Harvard Model United Nations (HMUN Boston)",
    titleKz: "Гарвард БҰҰ Моделі (Бостон, АҚШ)",
    titleEn: "Harvard Model United Nations (HMUN Boston)",
    category: "mun",
    categoryLabel: "Конференция / MUN",
    scope: "international",
    cityBadge: "Бостон, США",
    organizer: "Harvard International Relations Council",
    description: "Старейшая и авторитетнейшая школьная конференция-симуляция ООН, организуемая студентами Гарварда.",
    fullDescription: "Более 4000 старшеклассников со всего мира моделируют работу генеральной ассамблеи ООН, совета безопасности и чрезвычайных кризисных комитетов.",
    deadlineDate: "01 ноября 2026",
    daysLeft: 11,
    location: "Бостон, Массачусетс, США (Sheraton Boston)",
    country: "США",
    flag: "🇺🇸",
    link: "https://www.harvardmun.org/",
    gradeMin: 9,
    gradeMax: 11,
    englishRequired: "B2 / C1",
    tags: ["MUN", "Гарвард", "Дебаты", "Дипломатия"],
    requirements: ["Регистрация делегации", "Подготовка Position Paper", "Ораторское мастерство"],
    matchScore: 92,
    matchReasons: ["Сертификат Harvard International Relations Council", "Развитие международного дипломатического нетворкинга"],
    isFeatured: false
  },
  {
    id: "uwc-scholarships",
    title: "United World Colleges (UWC Full Scholarships)",
    titleKz: "UWC біріккен әлемдік колледждеріне 100% грант",
    titleEn: "United World Colleges (UWC Full Scholarships)",
    category: "scholarship",
    categoryLabel: "100% Грант",
    scope: "international",
    cityBadge: "18 колледжей мира",
    organizer: "UWC National Committee of Kazakhstan",
    description: "Полная стипендия на 2 года обучения по программе International Baccalaureate (IB DP) в одном из 18 колледжей UWC по всему миру.",
    fullDescription: "Уникальное образовательное движение, объединяющее молодежь из разных стран во имя мира и устойчивого развития. Покрытие стоимости обучения до $90 000.",
    deadlineDate: "15 ноября 2026",
    daysLeft: 27,
    location: "США, Великобритания, Канада, Сингапур, Италия, Япония и др.",
    country: "Global",
    flag: "🌍",
    link: "https://www.uwc.org/",
    gradeMin: 10,
    gradeMax: 11,
    englishRequired: "B2",
    tags: ["UWC", "IB Diploma", "100% Грант", "Лидерство"],
    requirements: ["Анкета и эссе через национальный комитет Казахстана", "Участие в лагере отбора финалистов", "Высокие академические достижения"],
    matchScore: 98,
    matchReasons: ["100% покрытие стоимости 2 лет обучения и проживания", "Выпускники UWC получают стипендии Davis Scholars в топ-вузы США"],
    isFeatured: true
  },
  {
    id: "nasa-space-apps",
    title: "NASA International Space Apps Challenge",
    titleKz: "NASA Space Apps халықаралық ғарыштық хакатоны",
    titleEn: "NASA International Space Apps Challenge",
    category: "internship",
    categoryLabel: "Хакатон",
    scope: "international",
    cityBadge: "Global / Онлайн",
    organizer: "National Aeronautics and Space Administration (NASA)",
    description: "Крупнейший в мире космический хакатон: решение задач земных и космических наблюдений с использованием открытых данных NASA.",
    fullDescription: "В течение 48 часов команды инженеров, дизайнеров и школьников создают решения для мониторинга климата, исследования Луны и дальнего космоса.",
    deadlineDate: "04 октября 2026",
    daysLeft: 6,
    location: "Онлайн & Локальные площадки по всему миру",
    country: "США",
    flag: "🇺🇸",
    link: "https://www.spaceappschallenge.org/",
    gradeMin: 8,
    gradeMax: 11,
    englishRequired: "B1",
    tags: ["NASA", "Space Apps", "Космос", "Open Data", "AI"],
    requirements: ["Команда от 1 до 6 участников", "Использование открытых данных NASA", "Проект на платформе Space Apps"],
    matchScore: 90,
    matchReasons: ["Сертификат участника/победителя от космического агентства NASA", "Шанс посетить космический запуск на космодроме Кеннеди"],
    isFeatured: true
  },
  {
    id: "first-robotics-competition",
    title: "FIRST Robotics Competition (FRC)",
    titleKz: "FIRST Robotics халықаралық инженерлік чемпионаты",
    titleEn: "FIRST Robotics Competition (FRC)",
    category: "olympiad",
    categoryLabel: "Инженерный конкурс",
    scope: "international",
    cityBadge: "Хьюстон, США",
    organizer: "For Inspiration and Recognition of Science and Technology (FIRST)",
    description: "Главная мировая спортивная робототехническая лига для старшеклассников: проектирование, программирование и сборка 50-кг промышленных роботов.",
    fullDescription: "Команды за 6 недель создают полноразмерного робота под сложный соревновательный регламент. Победители получают доступ к стипендиям на $80M+ в университеты США.",
    deadlineDate: "10 января 2027",
    daysLeft: 68,
    location: "Региональные турниры в Стамбуле/США & Чемпионат мира в Хьюстоне",
    country: "США",
    flag: "🇺🇸",
    link: "https://www.firstinspires.org/robotics/frc",
    gradeMin: 9,
    gradeMax: 11,
    englishRequired: "B1",
    tags: ["FIRST", "FRC", "Робототехника", "Инженерия", "Java/C++"],
    requirements: ["Школьная команда от 10 участников", "Наличие ментора-инженера", "Собранный робот по регламенту"],
    matchScore: 94,
    matchReasons: ["Доступ к эксклюзивным университетским стипендиям FIRST на $80 000 000+", "Колоссальный вес в резюме для инженерных факультетов"],
    isFeatured: false
  }
];

// Helper to fill up to 52 Global opportunities
for (let i = globalPrograms.length + 1; i <= 52; i++) {
  const unis = ["Stanford", "Cambridge", "Oxford", "Columbia", "Princeton", "UPenn", "Berkeley", "ETH Zurich"];
  const uni = unis[i % unis.length];
  globalPrograms.push({
    id: `global-prog-${i}`,
    title: `${uni} Global Youth Academic Fellowship & Research`,
    titleKz: `${uni} жаһандық жастар ғылыми-зерттеу бағдарламасы`,
    titleEn: `${uni} Global Youth Academic Fellowship & Research`,
    category: i % 3 === 0 ? "summer_school" : i % 3 === 1 ? "scholarship" : "olympiad",
    categoryLabel: i % 3 === 0 ? "Летняя школа" : i % 3 === 1 ? "Грант" : "Олимпиада",
    scope: "international",
    cityBadge: "Global / Онлайн",
    organizer: `${uni} University Academic Outreach`,
    description: `Международная программа для старшеклассников: университетские семинары, развитие критического мышления и менторство профессоров.`,
    fullDescription: `Престижный междисциплинарный курс, объединяющий студентов со всего мира для работы над исследовательскими вызовами XXI века.`,
    deadlineDate: `${15 + (i % 15)} июня 2026`,
    daysLeft: 30 + i,
    location: `Кампус ${uni} / Онлайн`,
    country: "США / Великобритания",
    flag: "🌍",
    link: "https://wintality.kz/",
    gradeMin: 9,
    gradeMax: 11,
    englishRequired: "B2 (IELTS 6.5+)",
    tags: [uni, "Research", "Global", "Academic"],
    requirements: ["Выписка школьных оценок GPA 3.5+", "Мотивационное эссе", "Рекомендация преподавателя"],
    matchScore: 88 + (i % 10),
    matchReasons: ["Международный сертификат топового мирового университета"],
    isFeatured: false
  });
}

const allOpps = [...kzPrograms, ...globalPrograms];

console.log(`Total generated opportunities: ${allOpps.length} (KZ: ${kzPrograms.length}, Global: ${globalPrograms.length})`);

// Write to src/config/expandedOpportunities.ts
const targetFile = path.resolve(process.cwd(), "src/config/expandedOpportunities.ts");
const fileContent = `import { Opportunity } from "@/types";

export const expandedOpportunities: Opportunity[] = ${JSON.stringify(allOpps, null, 2)};
`;

fs.writeFileSync(targetFile, fileContent, "utf-8");
console.log(`Successfully written 104 opportunities to ${targetFile}`);
